# Generated by Django 3.0.8 on 2020-07-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0002_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='_type',
            field=models.CharField(choices=[('init', 'init.d'), ('systemctl', 'systemctl')], default='systemctl', max_length=10),
        ),
    ]
