# Generated by Django 3.0.8 on 2020-07-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0003_service__type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='start_on_stop',
            field=models.BooleanField(default=True),
        ),
    ]
